# Generated by Django 2.0.3 on 2019-02-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190210_0747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElseItems',
            new_name='ElseItem',
        ),
    ]
