# Generated by Django 2.0.3 on 2019-02-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190210_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='elseitem',
            name='type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
