# Generated by Django 2.0.3 on 2019-02-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_elseitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elseitem',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='elseitem',
            name='large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='elseitem',
            name='small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
