# Generated by Django 2.0.3 on 2019-02-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190210_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElseItem',
        ),
    ]
