# Generated by Django 2.0.3 on 2019-02-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_elseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='type',
        ),
    ]
