# Generated by Django 2.0.3 on 2019-02-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_dinnerplatter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('items', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dinnerplatter',
            options={'ordering': ['small']},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['small']},
        ),
        migrations.AlterModelOptions(
            name='sub',
            options={'ordering': ['small']},
        ),
    ]
