# Generated by Django 2.0.3 on 2019-02-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190217_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={'ordering': ['large']},
        ),
    ]
