# Generated by Django 2.0.3 on 2019-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20190220_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('type', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('items', models.CharField(max_length=64)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
